Repository workshopapps/avatarai.web, pull requests merged in 2022-11, with the labels that each got.

#21 fix: resolving depency folder location
  .github/workflows/main.yml
Labels: enhancement, devops

#42 feat(fro-11): FAQs
  frontend/src/components/faq/FaqGetInTouch.jsx
  frontend/src/components/faq/FaqHero.jsx
  frontend/src/components/faq/FaqNewsletter.jsx
  frontend/src/components/faq/QuestionCard.jsx
  frontend/src/components/faq/QuestionSection.jsx
  frontend/src/components/faq/index.jsx
  frontend/src/components/faq/questions.js
Labels: enhancement

#46 feat(fro-11): FAQs - Improve styling
  frontend/package.json
  frontend/postcss.config.cjs
  frontend/public/magnifying-glass.svg
  frontend/public/tapart.svg
  frontend/src/App.jsx
  frontend/src/components/faq/FaqHero.jsx
  frontend/src/components/faq/QuestionCard.jsx
  frontend/src/components/faq/QuestionSection.jsx
  frontend/src/components/faq/index.jsx
  frontend/src/index.css
  frontend/tailwind.config.cjs
Labels: bug, enhancement

#116 feat(fro-11): Fix title color
  frontend/src/components/faq/FaqHero.jsx
Labels: bug, enhancement

#137 bug: fix color issues on text
  frontend/src/components/faq/FaqGetInTouch.jsx
  frontend/src/components/faq/FaqHero.jsx
  frontend/src/components/faq/FaqNewsletter.jsx
  frontend/src/components/faq/QuestionSection.jsx
Labels: bug

#161 install storybook
  frontend/.npmrc
  frontend/.storybook/main.cjs
  frontend/.storybook/preview-head.html
  frontend/.storybook/preview.cjs
  frontend/package.json
  frontend/src/stories/Button.jsx
  frontend/src/stories/Button.stories.jsx
  frontend/src/stories/Header.jsx
  frontend/src/stories/Header.stories.jsx
  frontend/src/stories/Introduction.stories.mdx
  frontend/src/stories/Page.jsx
  frontend/src/stories/Page.stories.jsx
  frontend/src/stories/assets/code-brackets.svg
  frontend/src/stories/assets/colors.svg
  frontend/src/stories/assets/comments.svg
  frontend/src/stories/assets/direction.svg
  frontend/src/stories/assets/flow.svg
  frontend/src/stories/assets/plugin.svg
  frontend/src/stories/assets/repo.svg
  frontend/src/stories/assets/stackalt.svg
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
Labels: enhancement

#181 add loading animation component
  frontend/package.json
  frontend/public/loading.lottie
  frontend/src/App.jsx
  frontend/src/components/desktop_5/Desktop5.jsx
  frontend/src/components/loading/Loading.jsx
Labels: enhancement

#182 feat: add dashboard 5
  frontend/src/App.jsx
  frontend/src/components/desktop_5/Content.jsx
  frontend/src/components/desktop_5/Desktop5.jsx
  frontend/src/components/loading/Loading.jsx
Labels: enhancement

#205 feat: login flow screens and login form validation
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/LoginPage/CheckEmail.jsx
  frontend/src/components/LoginPage/ForgotPassword.jsx
  frontend/src/components/LoginPage/Login.jsx
  frontend/src/components/LoginPage/PasswordReset.jsx
  frontend/src/components/LoginPage/ResetPassword.jsx
  frontend/src/components/sign-up/sign-up_first.jsx
Labels: enhancement

#216 feat: properly route dashboards
  frontend/src/components/Desktop_3/Content.jsx
  frontend/src/components/Desktop_3/Desktop3.jsx
  frontend/src/components/desktop_2/DD2Content.jsx
  frontend/src/components/desktop_5/Desktop5.jsx
Labels: enhancement
